name: Frontend Security Scan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  schedule:
    - cron: '0 2 * * 1' # Corre semanalmente los lunes
  workflow_dispatch: # Ejecución manual si lo necesitas

permissions:
  contents: read
  security-events: write

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    name: Secret Scanning
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
        continue-on-error: true

  eslint-check:
    runs-on: ubuntu-latest
    name: ESLint Code Quality
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (monorepo)
        run: npm ci

      - name: Run ESLint on all apps
        run: npm run lint --workspaces --if-present
        continue-on-error: true

      - name: Manual ESLint check for apps
        run: npx eslint ./apps --ext .js,.jsx,.ts,.tsx
        continue-on-error: true

  codeql-analysis:
    runs-on: ubuntu-latest
    name: CodeQL Security Analysis
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: security-and-quality

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (monorepo)
        run: npm ci

      - name: Build all apps for analysis
        run: npm run build --workspaces --if-present
        continue-on-error: true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:javascript'

  dependency-check:
    runs-on: ubuntu-latest
    name: Dependency Vulnerabilities & Dependabot
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (monorepo)
        run: npm ci

      - name: Audit root dependencies
        run: npm audit --audit-level=moderate || true

      - name: Audit workspace dependencies
        run: npm audit --audit-level=moderate --workspaces || true

      - name: Check for outdated packages in root
        run: npm outdated || true

      - name: Check for outdated packages in workspaces
        run: npm outdated --workspaces || true

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
